apiVersion: v1
kind: Pod
metadata:
  name: podonspecificnode
spec:
  containers:
  - name: sise
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
  nodeSelector:
    run: node-3

# kubectl label nodes <node> run=here
