apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  containers:
  - name: simpleservice
    image: nginx:1.14
    ports:
    - containerPort: 80
      resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
  - name: shell
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"