apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: test
      spec:
        containers:
        - name: test
          image: nginx:1.14
          ports:
          - containerPort: 80
        resources:
        limits:
          memory: "64Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: simpleservice
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: test

