apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-dep
  template:
    metadata:
      labels:
        app: tomcat-dep
    spec:
      containers:
      - name: tomcatcontainer
        image: tomcat
        ports:
        - containerPort: 8888
      resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
